### ISSUE TITLE
FYI - HTML Primer - Content Sectioning Video is not available

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#13]
Hello **Susan**,  it looks like the video link for content section in the notes is not available. You may check the *Sectioning & Semantics* section, in the [Content Sectioning](https://www.youtube.com/embed/rCJq6wxjmHg?rel=0&showinfo=0) for the missing or wrong link.

Thanks

**Comment by susanBuck** [comment]
Checking on this now, will report back when it's fixed.

**Comment by susanBuck** [comment]
Fixed now - thanks for the heads up! 

I'm also going through and doing a double check on all the videos in the _HTML Primer_ since there's been a couple problems with the video links this semester so far. Not sure why this is happening - it's possible I had been hosting these particular videos on a different YouTube account which I've since deleted, not realizing they were still being linked from the primer.
