### ISSUE TITLE
Confusing terminology in the VPS hosting article?

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#16]
I am going through this reading about [VPS Hosting](https://www.namecheap.com/hosting/what-is-vps-hosting-definition/)

and per article " *VPS hosting relies on a hypervisor to take resources from the physical server and provide each website with access to an emulated server (the VM). These physical servers are often held in a data centre and divided equally between several virtual compartments (known as **server virtualization**). Each compartment is rented out, and server software is setup on them separately so that each unit is capable of functioning as an independent unit. **Each individual VPS is called a container, and the server each container is held within is known as a node**.*",

 I think the author is using virtualization and containerization terminology interchangeably?  I think it may cause some confusion to some readers who may not know the difference.

**Comment by susanBuck** [comment]
I agree, that part is confusing. 

For anyone reading this and wondering why it's confusing...

The article is talking about a specific type of VPS (Virtual Private Servers) that use **VMs or Virtual Machines**.

With a Virtual Machine, you can run an isolated instance of an operating system within another operating system. Think of it as a computer within a computer. As an example, in lecture when I've switched to a Windows install on my Mac computer, I'm using a Virtual Machine.

Same thing with our DigitalOcean servers - our "Droplets" are Virtual Machines running Linux on a "host" Linux operating system that powers the whole server.

Another type of VPS or virtualization technique is **Containers**. With containers, you also have the "computer within a computer" result, but the difference is your "guest" machine is sharing the same kernel as the operating system on your "host" machine.

It's because of this that Containers require the host and guest machine to both use the same operating system. You could run a Linux container on a Linux host machine, but you couldn't - for example - run Windows on Mac.

A pro of containers is they're more lightweight than virtual machines.
A con of containers is you are limited to the same operating system for the host and guest machines.

Going back to the article, the use of the term "container" is confusing because the rest of the article is speaking specifically to the VM type of virtualization, not containers. Not sure what their source/reasoning is for that. : )

**Comment by mgarimelHES** [comment]
Thanks **Susan**!
