### ISSUE TITLE
Command line syntax and configuring SSH - questions

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#17]
I am seeking support with configuring SSH. The syntax for running command line arguments in my terminal (I am using MAC) is different than what's shown in lectures, which might be adding to my confusion. In this post, I:
1. Show examples of the different syntax in my terminal and resulting output
2. Outline questions about the syntax
3. Share challenges with SSH configuration 

### Examples of different syntax
Below are four examples of command line arguments to change directories: from _desktop_ to a folder on the desktop called _programming_ where I store class materials. The arguments have two placeholders to conceal personal information: _computer_ and _user_. I have included the result or error as an indented line beneath the code.

1. `computer:desktop user$ cd ~./programming`
> **Outputs error:** file does not exist

2. `computer:desktop user$ cd ~./desktop/programming`
>  **Outputs error:** file does not exist

3. `computer:desktop user$ cd programming`
> **Works:** changes to the programming directory

4. `computer:desktop user$ cd ./programming`
> **Works:** changes to the programming directory

### Questions about the syntax
After doing research about my examples, here are questions I have regarding functionality.

1. **Missing syntax in examples 3-4:** I am confused by why examples 3 and 4 work, since they are missing the `~` syntax that has been shown in lectures. Similarly, I am not sure why examples 3 and 4 have the same result, since one contains the `./` syntax.
2. **Examples 1-4: changing the way the terminal displays information?** My _current directory_ name is located in between _computer_ and _user_. Can I alter the settings of my terminal to hide certain information, for example _computer_?

### Implication for SSH configuration
I hope that support with the above questions will help with SSH configuration. Below, I have copied the command line arguments I have executed (and resulting errors) to try to configure my SSH, similar to what was presented in lecture.

**Location of the SSH directory:**  _desktop_ > _programming_ > _PHP_ > _ssh_

`computer:desktop user$ cd programming`
`computer:programming user$ cd php`
`computer:php user$ cd ssh`
`computer:ssh user$ ~/.ssh/config`
`-bash: /Users/user/.ssh/config: No such file or directory`
`computer:ssh user$ ~/.desktop/programming/php/ssh/config`
`-bash: /Users/user/.desktop/programming/php/ssh/config: No such file or directory`

Since I am new to working in the command line, I am hesitant about taking the next step to configure. All support and guidance is greatly appreciated!

**Comment by susanBuck** [comment]
Hi @ngal2021 - Thanks for the clear/detailed question.

Let's breakdown each command you referenced, starting with:

```bash
computer:desktop user$ cd ~./programming
```

This does not work because it's an absolute path, where ~ references your home directory. In effect, this is saying _"Change into a directory called `programming` within my home directory"_ which does not exist. The period after the `~` is also not necessary.

Next:

```bash
computer:desktop user$ cd ~./desktop/programming
```

When referencing the home directory, do not include a period. This should just be `cd ~/desktop/programming`.

Next:

```bash
computer:desktop user$ cd programming
```

This works/is correct because you're currently on your desktop and you move into the programming directory.

Finally:

```bash
computer:desktop user$ cd ./programming
```

This also works because `./` is a way of referencing your current directory. So in this example, you're on the desktop, so `./programming` looks for the directory `programming` in your current directory.

## Implications for SSH keys

RE:
> Location of the SSH directory: desktop > programming > PHP > ssh

Your _ssh_ directory should not exist in desktop/programming. It should exist at this path: `~/.ssh` (a folder called `.ssh` within your home directory).

To get there, run:

```bash
$ cd ~/.ssh
```

If the directory does not exist, first run:

```bash
$ mkdir ~/.ssh
```

## Changing the way terminal displays information

RE:
> My current directory name is located in between computer and user. Can I alter the settings of my terminal to hide certain information, for example computer?

Yes, you can - I'll reply to that separately with more info, but wanted to get the above information posted to you as soon as possible. : )

**Comment by susanBuck** [comment]
**RE: Customizing the way terminal displays information:**

From the output you shared, I see you're on a Mac using Terminal that is running **bash** as the underlying shell program. To customize your output, open the file `.bash_profile` from within your home directory:

```bash
$ code ~/.bash_profile
```

Within this file, look for a line defining a variable PS1 and update it to look like this:

```bash
export PS1='\w $ '
```

If no such line exists, add it.

This line dictates the format of your prompt. The `/w` references your current path, so in this example, your prompt will always include your current path and nothing else (e.g. not your computer name or user name). For more details on this check out: [Controlling the Prompt](http://www.gnu.org/software/bash/manual/bash.html#Controlling-the-Prompt)

**Save your changes then completely close and re-open Terminal for the changes to take effect.**

For anyone else reading this, if you're also on Mac/Terminal but your underlying bash program is Zsh, your instructions for customizing your prompt will be a little different. I'll add a module to this week's material that will go over how to tell if you're on zsh or bash, as well as more details on these customizations for anyone that is curious.

**Comment by gotgits** [comment]
Is there some advantage to customizing Terminal to bash instead of zsh? 

Also my ssh:hes-on-DigitalOcean CL appears like this:
root@lemp-ubuntu-s-1vcpu-1gb-nyc1-01:/var/www#

The course video display this:
root@hes:/varwww#

I followed the instructions, and everything seems to be working correctly, so I am curious if this makes a difference to my working environment.

**Comment by susanBuck** [comment]
@gotgits - I think the opposite actually - there are some benefits to using zsh over bash. [Here's a useful post on this...](https://medium.com/@harrison.miller13_28580/bash-vs-z-shell-a-tale-of-two-command-line-shells-c65bb66e4658). 

**RE: the different prompt on DigitalOcean -**
In my examples the `hes` is coming from the name I gave the Droplet when I created it. It looks like you left yours to the default/pre-generated name of `lemp-ubuntu-s-1vcpu-1gb-nyc1-01`. 

DigitalOcean uses this name to not only label your Droplet in their control panel, but it also sets it as the default host name on your server, which is what you're seeing in the prompt.

To update your host name on the server run this command:

```bash
$ hostname some-new-name
```

To see your current host name just run:

```bash
$ hostname
```

After you update the hostname, you have to close and re-open the Terminal window in VSCode to see the changes in your prompt. 

Note that changing the host name on the server won't change the name of the Droplet as it's listed in DigitalOcean's control panel. To change it there, go to the page for the Droplet in DigitalOcean and click the name (it'll change to an edit field).

**Comment by owen-mcg** [comment]
> **RE: Customizing the way terminal displays information:**

I knew this must be possible, but had absolutely no idea how to do it.

**Comment by ngal2021** [comment]
@susanBuck, thank you for all of the information! 

**RE: Command Line Syntax**: Your clarification has helped me very much - I am feeling more comfortable with the syntax now.

**RE: SSH Configuration**: I was able to configure the SSH in the correct location on my computer.

**RE: Customization**: Very interesting! I'm going to try customizing my terminal soon, as I think reducing the amount of text in my terminal might help me going forward.

Thanks again!

**Comment by susanBuck** [comment]
@ngal2021 - Glad you got it sorted out and this was helpful! Keep the questions coming as you run into them. : )
