### ISSUE TITLE
index / index-view

### ISSUE THREAD

**Issue by owen-mcg** [susanBuck/e2-fall21#22]
I have a strange thing happening with my php files. When I run bank.php and bank-view.php, everything works fine. bank.php seems to reference bank-view.php in what Susan describes in the lecture and the notes as the controller / view files. 

But then when I try to set up index.php and index-view.php (still with the require statement), when I go to the url that I'm pretty sure is right (I've tried a few to see if anything changes), it downloads the file instead. index.php does seem to be referencing index-view.php, because when it downloads the file, it only contains the contents of index-view, despite being named as index.php. 

Any clues?

**Comment by susanBuck** [comment]
Can you share the URL you're trying to access?

Also, can you update your repository in Github with your latest changes and share the URL to your repo? That way we can look at your index/index-view.php files exactly as you see them.

**Comment by owen-mcg** [comment]
Here's my repo url: https://github.com/owen-mcg/e2 
Here's my project url: http://e2p1.projectpage.me/index.php

Prepare to download my filler html structure lol.

**Comment by susanBuck** [comment]
@owen-mcg - Thanks! Taking a look now and will report back shortly.

**Comment by owen-mcg** [comment]
Thanks @susanBuck I really, really appreciate it.

**Comment by susanBuck** [comment]
I notice when I visit http://e2p1.projectpage.me it redirects me to http://e2.projectpage.me/p1/

This leads me to believe there might be some problem in how your subdomains are set up.

Can you share a screenshot of your DNS settings from within Namecheap?

Also, on your server can you run the command `code /etc/nginx/sites-available/hes` to open the contents of your _hes_ sites config file and share the contents here? ([This was the file we created when configuring subdomains](https://hesweb.dev/e2/notes/infrastructure/subdomains))

**Comment by owen-mcg** [comment]
Oh my @susanBuck I'm sure this is the problem. I don't think I did this step. I'm going to try get this sorted out and I'll report back with results.

**Comment by susanBuck** [comment]
Sounds good. I'll hold for follow-ups. : )

**Comment by owen-mcg** [comment]
Ok well, I've still got something screwed up. I'm trying to start over and get things reconfigured correctly, but I'm missing something I guess. It's no longer downloading the file, which is good, but is now giving me a 404. I've uploaded screenshots as well. Thanks for taking time to help get me sorted out
![Screen Shot 2021-09-22 at 12 50 03 PM](https://user-images.githubusercontent.com/70607067/134395674-3a26c385-c8cf-4608-8f8f-0e34cb617fec.png)
.
![Screen Shot 2021-09-22 at 12 49 06 PM](https://user-images.githubusercontent.com/70607067/134395712-00ba39b8-5fc2-4dad-83ad-eee03edd92ed.png)

**Comment by syedyasirkamal** [comment]
For some reason, the autoformatting of PHP on my VS is not working. It will show that redundant closing tag even though all my settings are correct for Format on Save.

**Comment by susanBuck** [comment]
@owen-mcg I can't spot any obvious problems in your _hes_ file; thanks for sharing that.

Not sure what's missing here - would it be okay if I log into your server to double check everything/debug? I'll report back on what I find.

If so, just run the following command while connected to your server. It will add my public key to your server's list of authorized keys so that I will be able to log in.

```
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBCP3tIaVVnmHAirsPY1OqbTX0C5j+B/zVtuCm/BLO4ECkrb7qfqVgJWZ+ZyN2GUY5sfby3X5WAw1berSnZ123N+lMufCK1jH+dIqROhlAJ6e/MXtk8IIPnx4OHHxeRnQIeBPXRqY+6351daWtpvVzs6JzPAlkES6VlB/dLsYoD1j8LcOrDpjnVVAuS6K5sd3Q6DA6u4zxvbhWJBVrO02dckxvWsuI34CDOdP2ApUjdZ0TSMaKKh0Zitu2J+GoOKeGTq4X8sj0k1aQ1IQpuXiVdJ2aavUIlarRBitSu2/6MUDEEITJXLyZM+I4w83aZnW3KOXu3q0WTWzK3qjQvKIX susanbuck@fas.harvard.edu" >> ~/.ssh/authorized_keys
```

(Make sure you grab the full command, starting with `echo` and ending with `>> ~/.ssh/authorized_keys"`

**Comment by owen-mcg** [comment]
Sure I'd be happy to! That's very kind of you. 

(I did it; there was neither fanfare, nor sirens, so hopefully I did it right!)

**Comment by susanBuck** [comment]
@owen-mcg - Excellent - I was able to log in and am doing some troubleshooting now. Will report back shortly.

**Comment by susanBuck** [comment]
So far everything on the server is checking out as correct - but I'm still digging. 

Here's what I've observed: 
+ ✅ http://e2practice.projectpage.me/bank.php works
+ ✅ http://e2practice.projectpage.me returns a 404 not found page, but that's to be expected because the practice directory has no index file.
+ ❌ http://e2p1.projectpage.me does not work as expected, redirecting to http://e2.projectpage.me/p1 - which is not what we want.

**Somewhere, there's some setting that is causing that redirect and we need to find it.** 

In Namecheap, when looking at this domain under the "Domain" tab can you make sure there are no redirect settings here:

![image](https://user-images.githubusercontent.com/237711/134515716-8318f5a6-fc96-4cff-9720-ce200482f3f3.png)

Also, while we're checking everything, go ahead and share a screenshot of the full page under the "Advanced DNS" tab.

In the meantime, I'll continue digging on the server side of things. : )

**Comment by owen-mcg** [comment]
No redirects. I think I had a redirect briefly when I was trying to get my github page working with the domain, but it didn't work, so I quickly abandoned that approach (within minutes of trying it). Hopefully that didn't screw something up permanently. I really appreciate your help with all this. 
![Screen Shot 2021-09-23 at 9 54 47 AM](https://user-images.githubusercontent.com/70607067/134531901-8d3d5262-2452-421d-8499-884d313e8fc9.png)

**Comment by susanBuck** [comment]
Ok - that initial redirect you had put in there is the source of the issue. Even though it's deleted now, it must be a cache issue.

When I tried loading http://e2p1.projectpage.me in a different browser, it worked. 🎉😀 
Here it is in Safari: 
<img width="857" alt="image" src="https://user-images.githubusercontent.com/237711/134533426-6d1339ff-60f8-4a2c-ba59-fef5ed94ac14.png">

Try clearing your browser cache and restarting your browser - that should clear it up. 👍

**Comment by owen-mcg** [comment]
Oh my god it's working. Thank you so much for your help!
