### ISSUE TITLE
Rubrik for Project1

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#26]
Hello **Susan**,

 Will there be any *Rubric* for grading on Project1 . I think you have mentioned something in those lines in week4 recordings. But I would like to double check and make sure to cover those in the Project1.

Thanks a lot,

**Comment by susanBuck** [comment]
The rubrik is pulled pretty directly from the project specifications. Here's what a perfect project would look like:

```
✓ Readme file complete, written to spec, with proper Markdown formatting
✓ App follows the correct url convention
✓ Game simulation operates as expected
✓ No bugs or errors are present
✓ Page includes game mechanics information
✓ Demonstrates proficiency with the PHP concepts covered so far
✓ Correct separation of concerns; controller file contains only logic; view file contains only display code
✓ Code follows any best practices outlined in lecture/notes
```

I don't publish point specifics ahead of time because a) I think the expectations are pretty clear to make perfect marks and b) any point deductions will vary depending on how close/far off one is from the spec.
