### ISSUE TITLE
php 7.x vs php 8

### ISSUE THREAD

**Issue by owen-mcg** [susanBuck/e2-fall21#28]
It seems like we're using php 7.x on our servers. Would there be any harm in upgrading to 8? Would there be any benefit?

**Comment by susanBuck** [comment]
For the simple examples we're working with, there wouldn't be any harm or benefit. The difference wouldn't really be discernable.

If you had an established application, doing any sort of system upgrade can potentially introduce unexpected bugs. Because of this, it's always good to research ahead of time what changes will be introduced. It's also good to have a testing system in place that could ensure your application would continue to work as expected on the upgrade (testing is something we'll look at later in the semester).

The benefit of upgrading is you'd get to take advantage of the optimizations and additional features that PHP 8 offers. Here's a good write-up on the additions: https://kinsta.com/blog/php-8/
