### ISSUE TITLE
Collecting numeric value from each turn and sum those values to decide winner

### ISSUE THREAD

**Issue by gotgits** [susanBuck/e2-fall21#35]
How do I collect the values from each turn and sum those values for each turn by each player to decide which player finishes first?

In order to get a minimal viable product working I created for loops with rand(1, 25)for each turn and a conditional statement. This works well with a conditional statement for one round.

I added another conditional statement for summing totals but with array to string errors and no viable sums to determine a $winner.

Reviewing the Accumulating/displaying results for a multi-round game video helped but only with display.

[Link to Page](http://e2p1.metrognome.me/index-1.php)
[Link to Repository](https://github.com/gotgits/e2/commit/320683011c3f9084432c1abd7f611ea7b8e610e8)

## Screenshot Current Code
![Page appearance with single round conditional working](http://e2p1.metrognome.me/Screenshot-conditional-single-round.png)

**Comment by susanBuck** [comment]
To sum up values, you can use the + operator.

For example, here's a loop that adds _$i_ to a variable _$total_ each iteration through the loop:

```php
$total = 0;

for($i = 0; $i < 10; $i++) {
    # Increment $total by $i each iteration through the loop
    $total = $total + $i;
}
```

I'm not sure if that answers your question, as I'm trying to wrap my head around what you're trying to accomplish. (Side note: I've never played snakes and ladders before :-)

From your README file, here's what I think you're trying to do:

_Each player gets a series of random numbers, and those numbers are accumulated. The first players who total adds up to 25 wins._

To do this, I would use a while loop because there is an indeterminate end - we don't know how many turns it will take for the player to reach 25.

Something like this:

```php

# Initialize variables
$playerATotal = 0;
$playerATurnCount = 0;

# Go until playerA reaches 25
while ($playerATotal < 25) {

    # Add a random number to playerA's total each time
    $playerATotal = $playerATotal + rand(1, 25);

    # Increment how many "turns" they've had
    $playerATurnCount++;
}

var_dump("Turns it took player A to get to 25: $playerATurnCount");
```

Am I in the right ballpark in terms of what you're trying to accomplish? Let me know if I'm misunderstanding!

**Comment by gotgits** [comment]
Thank you, yes you seem to understand and I was trying a while loop. I started with the multi-dimensional array for conditional statements which I am not sure yet how I will integrate. Computing Totals are great for now.
