### ISSUE TITLE
Project 1 share thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall21#42]
Hi everyone,

In this thread, I'd like you all to check out each other Project 1s as an opportunity to explore outside code.

To kick things off, below are two excellent projects to dig into, both tackling the "War" card game.

Version 1:
+ http://e2p1.abdellgautier.com
+ https://github.com/AbdellGautier/e2/tree/main/p1

Version 2
+ http://e2p1.nhroyal.com
+ https://github.com/mike32jacobs/e2/tree/main/p1

Check out the app and then look through the code and make notes on any of the following:
+ Are there any parts of the code that you found interesting or taught you something new? 
+ Do you have any notes for improvement?
+ Are there any parts of the code that you don't understand? 
+ Are there any built in PHP methods that were used that you hadn't yet encountered? Explain what the method is and what it does.
+ Anything else that sticks out to you...

**Reply to this thread with your notes, and also include a link to your project on your server and in Github.**

**When coming to this thread, pick a project that has not already been responded to, pulling from the replies that come in.**

**Comment by mike32jacobs** [comment]
The first thing that I noticed about Abdell's project was that the look was much better than mine. I liked the inclusion of images for the suits. Hearts and diamonds displayed with red font while spades and clubs displayed with black font. 
Another thing that I noticed was that we built our decks in a similar fashion.
My code to make a deck
```php
// Dynamically create a deck of cards using a multidimensional array.

$cardNames = array('2','3','4','5','6','7','8','9','10','J','Q','K','A');
$cardSuits =array('Hearts','Spades','Diamonds','Clubs');

$deck = array();

// Note: To use all four suits, $suit < 4. To use just one suit, use $suit < 1.This plays the game with only hearts.

for ($suit = 0; $suit < 4; $suit++) {
    for ($value = 2; $value< 15; $value++){
        array_push($deck, array($cardNames[$value - 2], $cardSuits[$suit], $value));
    }
}
````
Abdell's code to make a deck
```php
// Define the card suits
$cardSuits = [
    "C",    // Clubs
    "D",    // Diamonds
    "H",    // Hearts
    "S"     // Spades
];
// Define the card rank and values
$cardRankValues = [
    "A_1", // The number after the "_" represents the value of the card
    "2_2",
    "3_3",
    "4_4",
    "5_5",
    "6_6",
    "7_7",
    "8_8",
    "9_9",
    "10_10",
    "J_11",
    "Q_12",
    "K_13"
];
// Will hold all the 52 cards
$deck = [];
// Build our stack of cards, based on the suits and ranks
foreach ($cardSuits as $cSuit) {
    foreach ($cardRankValues as $cRankValue) {
        array_push($deck, $cSuit . "_" . $cRankValue);
    }
}
```
One difference that I notice was that I ranked the A as the strongest card, and Abdell made the A the weakest card. This is something that may change based on the game. It immediately makes me wonder how I would build a deck for a game like blackjack which has card ranks that could be variable. An ace can be worth one or 11 in black jack. That means we would both have to add some more features to our deck if building a deck for blackjack.

**Comment by ngal2021** [comment]
@mike32jacobs and @AbdellGautier, as someone new to coding, it was exciting to go through your projects! 


Mike, I took a detailed look at your code, and I learned quite a bit.

### Great example of `array_shift`
I saw that this was a built-in PHP function, and it wasn't until I read through your code that I understood how it could be used (and you utilized it twice, which helped my understanding a lot).

1. When the cards are dealt one at a time to each player, dealing the top card
2. When the players play their cards, playing the 1st card in their piles

### Style recommendation for comments
Your comments are very clear, and it helped me understand your logic and your code choices. One recommendation I have is to shorten comments when you are able to in order to reduce the need to scroll. There are a few places where they could be shortened. For example, the comment on line 96:

```php
// Compare the values of player1Card and player2Card. The interesting thing will be how to compare cards. The result of the comparison will either add cards to one of the player's hands or discard them.
```
There are several descriptive comments below the one on line 96 that explain the logic of determining the result, so the comment on line 96 could be shortened to something like:

```php
// Compare player1Card and player2Card values to determine result
```

**Comment by ngal2021** [comment]
# Rock, Paper, Scissors project

I created "Rock, Paper, Scissors". There are ways to improve upon separation of concerns (@susanBuck, thank you for the feedback/suggestions in Canvas), and so I am looking forward to hearing ways I can improve!

Server: [http://e2p1.nicolaphp.me/](http://e2p1.nicolaphp.me/)
GitHub: [https://github.com/ngal2021/e2/tree/main/p1](https://github.com/ngal2021/e2/tree/main/p1)

**Comment by RaulPulidoB** [comment]
I created a version of Rock-Paper-Scissors too. In this version, the system displays the images of the random selection for each player and tells you who the winner is.

Server: [http://e2p1.raulpulido.me](http://e2p1.raulpulido.me)
GitHub: [https://github.com/RaulPulidoB/e2/tree/main/p1](https://github.com/RaulPulidoB/e2/tree/main/p1)

**Comment by ngal2021** [comment]
@RaulPulidoB, you developed an interesting function `gameCheck` to determine the winner. The function makes the code much more efficient than going through, checking all the game outcomes (which is what I did in my version). Your inclusion of images of the moves adds a lot of interest and makes the game more realistic!

**Comment by lyonsco** [comment]
These projects are very impressive! I reviewed @mike32jacobs's code, and was impressed by how complex the game logic was, but how effectively Mike broke it down into smaller pieces, with helpful comments that explained what each part of the code was doing. It made it much easier to follow all of the steps involved in the game.

The parts that were most helpful for me to see were the use of arrays for several facets of the game (starting with a multidimensional array created by pushing the card values and card suits into a $deck array; then arrays fo each player's hand, the cards they already played, and the cards remaining to be played). It was helpful to see how Mike then used the count function as a way to set up logic for the game based on the number of cards in these arrays.

Thank you for providing such great examples!

Here is the link to my project and Github repository. I have since updated the code with Professor Buck's help to reduce some of the repetition and to have the results display dynamically.

Server: http://e2p1.hesclyons.me/ 
Github Repository: https://github.com/lyonsco/e2/tree/main/p1 
Updated version of Project 1: http://e2practice.hesclyons.me/p1-refactored/

**Comment by AbdellGautier** [comment]
@mike32jacobs  It was great looking at your project, great job!

@ngal2021 Good job on your work; it was clean and effective in getting the job done.

@RaulPulidoB Very nice job at compacting the winner calculation in your code. When I saw the pictures, I smiled and said to myself, "That's clever!".

@lyonsco Well done. I loved the target number in blue. Many times, changing some colors can make a difference. I see that you refactored nicely in your p1-refactored folder, making the code cleaner in the view and the back-end, nice!

**Comment by harrison2705** [comment]
Thank you very much for sharing your work.

Going through Mike and Abdell’s projects, I was impressed by the way they organised the structure of each php page, which is very easy for readers to understand and follow. Additionally, I gained more insights into how “array_shift” can be used to take the first value of the array and assign it to a new variable. It can help to shorten the array by one unit and move everything down.

I also learned how to use @keyframes for animation and will apply this concept in my project 2 and 3. 

For project 1, I simply created a simple version of a marble game that was inspired by the popular series Squid Game. 

Server:  http://e2p1.huynguyenau.me
GitHub:  https://github.com/harrison2705/e2/tree/main/p1

Thank you.

**Comment by abarry25** [comment]
I also created a version of Rock-Paper-Scissors! Here you will see your throw, the computer's throw, and get a dynamically styled message based on the results.

Server: http://e2p2.tablespoon.me
GitHub: https://github.com/abarry25/e2/tree/main/p2

**Comment by ant513g** [comment]
The first thing I notice in the files are the various different types of loops being used. The first part I notice is foreach vs for. I thought that only a foreach loop would work on arrays, but these examples show other wise. In @mike32jacobs ’s I see that  a while loop is used, and I am curious how much of a different using a for loop vs while loop vs foreach loop would make, as the differences in these two project are not apparent.

For project 1, I created a Powerball Lottery example. 

Server: [http://e2p1.anadesign.me/](http://e2p1.anadesign.me/)
GitHub: [https://github.com/ant513g/e2/tree/main/p1](https://github.com/ant513g/e2/tree/main/p1)

**Comment by mgarimelHES** [comment]
ngal2021 - I am working on Rock, Paper and scissors as well, I liked your documentation  part and other approaches as well. 
my application - http://e2p1.hesweb.me

**Comment by syedyasirkamal** [comment]
I created the High Low game. 
The cards game makes no sense to me because I never played cards in my life.

This was my first time dealing with PHP so it was a bit of fun and challenge too

http://e2p1.kamalzadeh.me/index1.php

**Comment by gabichuela85** [comment]
For both @AbdellGautier and @mike32jacobs 's projects I really appreciated looking to see how they built their decks of cards. Especially seeing as one used a for loop while the other utilized a foreach loop. I attempted a card game at first, but I struggled to create a deck of cards, so this was very helpful to see how they went about it.

**Comment by allanmglass12** [comment]
Hello all, here are the two versions of my game - **Pass The Pigs** [Single Pig]:

_Version 1_

- [http://e2p2.allan.glass/](http://e2p1.allan.glass/)
- [https://github.com/allanmglass12/e2/tree/main/p1](https://github.com/allanmglass12/e2/tree/main/p1)

_Version 2_

- [http://e2p2.allan.glass/](http://e2p2.allan.glass/)
- [https://github.com/allanmglass12/e2/tree/main/p2](https://github.com/allanmglass12/e2/tree/main/p2)

I look forward to your feedback! :) - Allan

**Comment by wtang12340** [comment]
@allanmglass12 

You domain seems to be suspended so might want to get that fixed. But looking at the code, you didn't separate into two different files for separation of concerns. Probably better practice to do it that way. 

Here is my project 1 if anyone wants to take a look. 

- [http://e2p1.william-tang.com/](http://e2p1.william-tang.com/)
- [https://github.com/wtang12340/e2/tree/main/p2](https://github.com/wtang12340/e2/tree/main/p2)

**Comment by gotgits** [comment]
**@wtang12340**

I am so glad that you worked with the dice concept. I wish that your Github url was to your code rather than Susan's because I have been working on trying to utilize the dice concept to emulate progression across a board, with sums and haven't yet had success with StackOverflow or other searches and readings within php.net to actualize this endeavor. 
Here are my project 1 urls, I have only brushed the surface of my ultimate concept, but it is functional.

- [http://e2p1.metrognome.me](http://e2p1.metrognome.me)
- [https://github.com/gotgits/e2/tree/main/p1](https://github.com/gotgits/e2/tree/main/p1)

Thanks for updating your link. I have a much better grasp on adding scores and separating the computer scores in the index.php and the user input scores in the processing.php to calculate the results.

**Comment by wtang12340** [comment]
> **@wtang12340**
> 
> I am so glad that you worked with the dice concept. I wish that your Github url was to your code rather than Susan's because I have been working on trying to utilize the dice concept to emulate progression across a board, with sums and haven't yet had success with StackOverflow or other searches and readings within php.net to actualize this endeavor. Here are my project 1 urls, I have only brushed the surface of my ultimate concept, but it is functional.
> 
> * http://e2p1.metrognome.me
> * https://github.com/gotgits/e2/tree/main/p1

@gotgits Thanks for catching that, I updated my link.

**Comment by gotgits** [comment]
> > **@wtang12340**
> > I am so glad that you worked with the dice concept. I wish that your Github url was to your code rather than Susan's because I have been working on trying to utilize the dice concept to emulate progression across a board, with sums and haven't yet had success with StackOverflow or other searches and readings within php.net to actualize this endeavor. Here are my project 1 urls, I have only brushed the surface of my ultimate concept, but it is functional.
> > 
> > * http://e2p1.metrognome.me
> > * https://github.com/gotgits/e2/tree/main/p1
> 
> @gotgits Thanks for catching that, I updated my link.

I have somehow broken all of my subdomains and hes config file today while working on framework installation. I am currently trying to correct that
