### ISSUE TITLE
Parse error in vowelCount exercise

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#45]
I am getting a parse error related to the foreach loop in my vowelCount function, `(foreach($letters as index => $letter){`, that I am having trouble mitigating. I am trying to circle through each letter in letters.

### vowelCount
```php
function vowelCount(string $word)
{
    $letters = str_split($word);
    $countVowels = 0;

    foreach($letters as index => $letter) {
        if($letter == ['a', 'e', 'i', 'o', 'u']){
            $countVowels ++;
        }
    }

    return $countVowels;
}
```
### Parse error
`Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting '[' in /var/www/e2/practice/week7-exercises/vowel-count.php on line 11`

### Understanding working with arrays
The error might be a result of my confusion working with arrays. I do not full understand how to utilize a foreach loop on an array when the array only appears to have values. For my understanding, is the 'place' of where the value is located the key? For example in `array['cat', 'dog', 'bird']`, the key for the value 'cat' would be '0' since it is in the 0 position.

### Late request for support
I am a bit behind working on this exercise, so I understand that there isn't a lot of time for feedback/support before Week 7's assignment is due. Looking forward to feedback and seeing a solution in the upcoming lecture!

**Comment by susanBuck** [comment]
Hi @ngal2021 -

Still plenty of hours in the day left to get feedback. :-)

You are correct that the "place" of where the value is located is the key (aka the index).
You are also correct that given an array of `['cat', 'dog', 'bird']`, the key for the value 'cat' would be 0.

The error you're getting is coming from the fact that `index` in the line `foreach($letters as index => $letter) {` is not prefixed with a dollar sign. Once you add that, it will run without error. 

However, the function still won't operate as expected because of this boolean expression:

```
$letter == ['a', 'e', 'i', 'o', 'u']
```

Here we're comparing a string `$letter` to see if it's equivalent to an array of vowels, which would never be true. **A string can not be equivalent to an array.**

Instead what we want to do is **look for the presence of $letter within the vowels array**. To do that, you can use PHP's built-in [in_array](https://www.php.net/manual/en/function.in-array.php) function.

This function takes two parameters:
1. a "needle" (the thing you're looking for - in this case the string $letter) 
2. a "haystack" (what you're looking in - in this case - your array of vowels)

So the boolean expression could look like this:

```php
if (in_array($letter, ['a','e','i','o','u'])) {
    $countVowels ++;
}
```

**Comment by ngal2021** [comment]
Thank you so much, @susanBuck! This improved my understanding of how to work with arrays and how to utilize the **_in_array_** function.
