### ISSUE TITLE
Project 2 roadblocks: working with Boolean values

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#47]
I am having an issue working with Boolean values for Project 2. Here is a link to my game: [http://e2p2.nicolaphp.me/](http://e2p2.nicolaphp.me/)

The game appears to function okay for when the user wins the round and when the player loses to the computer, but it does not operate correctly when there is a tie, incorrectly rendering the html for the tie and lost scenarios. I think this is because I am incorrectly utilizing Boolean values, and I appreciate guidance on how to mitigate this issue. 

### process.php

Here is what I was trying to do in my code. I am setting `$tie` to `true` if the player's and computer's moves are the same, and setting `$winner` to `true` if the player's move beats the computer's move. This would result in the scenario that when `$tie` is `false` and `$winner` is `false`, the player and the computer do not tie, and the player does not win, so the computer wins. Here is the code in my 'process.php':

```php
<?php

session_start();

$playerMove = $_POST['choice'];

$computerMove = ['rock', 'paper', 'scissors'][rand(0, 2)];

$tie = $playerMove == $computerMove;

if (! $tie) {
    $winner = determineWinner($playerMove, $computerMove);
}

$_SESSION['results'] = [
    'winner' => $winner,
    'tie' => $tie,
    'playerMove' => $playerMove,
    'computerMove' => $computerMove,
];

header('Location: index.php');

function determineWinner($playerMove, $computerMove)
{
    if ($playerMove == 'rock' and $computerMove == 'scissors' or $playerMove == 'scissors' and $computerMove == 'paper' or $playerMove == 'paper' and $computerMove == 'rock') {
        $playerWon = true;
    } else {
        $playerWon = false;
    }
    return $playerWon;
}
```

### index.php

```php
<?php

session_start();

if(isset($_SESSION['results'])){
    $results = $_SESSION['results'];
    $winner = $results['winner'];
    $tie = $results['tie'];
    $playerMove = $results['playerMove'];
    $computerMove = $results['computerMove'];

    $_SESSION['results'] = null;
}

require 'index-view.php';
```

### index-view.php
In the view, I am using php so that: if `$tie` is `true`, it renders the tie result; if `$winner` is `true`, it renders the result of the player's win; if both `$tie` and `$winner` are `false`, it renders the result of the computer's win. 

I tried writing the html a few different ways, including utilizing 'else' at first, but I thought I needed to be more specific with the parameters of the Boolean values to mitigate the errors.

```html
<?php if(isset($results)) { ?>

        <h2>Results</h2>

        <ul>

            <li>You threw <strong><?php echo $playerMove ?></strong>.</li>
            <li>The other person threw <strong><?php echo $computerMove ?></strong>.</li>  

            <?php if($tie) { ?>

            <li>Your move is the same the other player's move. You tied!</li>

            <?php } if($winner) { ?>

            <li><strong><?php echo ucwords($playerMove) ?></strong> beats <strong><?php echo $computerMove ?></strong>. You won!</li>

            <?php } if((! $winner) and (! $tie)) { ?>

            <li><strong><?php echo ucwords($playerMove) ?></strong> is beaten by <strong><?php echo $computerMove ?></strong>. You lost, please try again!</li>

            <?php } ?>

        </ul>

<?php } ?>
```

### Some thoughts
**Account for the other possible scenario:** I am wondering if I need to account for the other possible (but unlikely scenario, unless there is some client-side alteration to the form submission) in my code:
`$tie` is `true` and `$winner` is `true`

**determineWinner():** In refactoring, I tried to remove 'tie' out of the determineWinner function, but this might be where the issue is coming into play.

**setting $winner == $tie:** I also tried setting the $winner variable to tie after the code: `$tie = $playerMove == $computerMove;`

### Other issues with `determineWinner()`:

**ternary operator:** I have tried to utilize the ternary operator to shorten the winner-checking logic (`(boolean expression) ? optionIfTrue : optionIfFalse`, but I am not sure how to handle the 'false' scenario. Do I need to utilize the ! operator?

```php
($playerMove == 'rock' and $computerMove == 'scissors' or $playerMove == 'scissors' and $computerMove == 'paper' or $playerMove == 'paper' and $computerMove == 'rock') ? $playerWon : (! $playerWon);
```
**Some pseudocode to make this more efficient:**
I think I could turn the moves into an array where the key is playerMove and the value is computerMove, then searching for instances of the key value pair. I am not sure how much more efficient this would make my code.

**Comment by susanBuck** [comment]
Hi @ngal2021 - FYI Looking at this now and will reply shortly.

**Comment by susanBuck** [comment]
In my tests, it looks like the three scenarios (tie, win, loss) are operating as expected:

**Tie**
![image](https://user-images.githubusercontent.com/237711/138596808-e66da9a0-882d-4c18-94fc-247d41089d91.png)

**Win**
![image](https://user-images.githubusercontent.com/237711/138596823-47b6e760-c166-4730-a122-fcee05a90c9c.png)

**Loss**
![image](https://user-images.githubusercontent.com/237711/138596837-c8d06483-d4a7-479a-b498-4a4cb97b3595.png)

Wondering if maybe you've changed something since you posted? Or - if I'm missing something, let me know : )

## Note 1
In your view, there are three outcomes, only one of which should be possible. Because of this, I suggest converting the three individual _if_ statements into a one _if/else if/else_ statement.

To understand what I mean, here are two simplified/pseudo code blocks demonstrating:

**How you have it**
```php
if($tie) {
   tie message
}

if($winner) {
   win message
}

if(!$winner and !$tie) {
    loss message
}
```


**Suggested alternative:**
```php
if($tie) { 
   tie message
} else if($winner) {
   win message
} else {
   loss message
}
```

This is more logical since only _one_ of the three options is possible. It's also more efficient because it will only have to evaluate the if/else branches until it finds true. 

In the way it's written now, it'd have to evaluate each individual if statement, even if - for example - the first one was true.

## Note 2
You mentioned that you refactored the tie scenario out of your _determineWinner_ function, but I actually think it should be there. Right now it feels like the logic for the game is separated into two different spots- first to determine if there's a tie, then if there isn't determining which move wins.

It feels cleaner to simply pass the two moves to determine winner and have it return either "tie", "player" or "computer".

So in your controller you'd have something like:
```php
$results = determineWinner($playerMove, $computerMove);
```

Then, in your view (again, simplified/pseudo code here):
```php
if($results == 'tie') {
   tie message
} else if ($results == 'player') {
   win message
} else {
   loss message
}
```



## Note 3
RE: your note about using a ternary operator in _determineWinner_ - I'm not sure that's a good fit here. Instead I think you want to apply the technique described here: https://hesweb.dev/e2/notes/php/code-design#boolean-ifelse-statements-as-simple-expressions

Before:
```php
if ($playerMove == 'rock' and $computerMove == 'scissors' or $playerMove == 'scissors' and $computerMove == 'paper' or $playerMove == 'paper' and $computerMove == 'rock') {
        $playerWon = true;
    } else {
        $playerWon = false;
    }
```

After:

```php
$playerWon = $playerMove == 'rock' and $computerMove == 'scissors' or $playerMove == 'scissors' and $computerMove == 'paper' or $playerMove == 'paper' and $computerMove == 'rock';
```

But this still assumes your function is returning _true_ or _false_, which, based on my above note, might not be the case anymore. Knowing that, I'd write the logic like this:

```php
if($playerMove == $computerMove) {
    return "tie";
} else if($playerMove == 'rock' and $computerMove == 'scissors' or $playerMove == 'scissors' and $computerMove == 'paper' or $playerMove == 'paper' and $computerMove == 'rock') {
     return "player";
} else {
    return "computer";
}
```

Note that I'm still not using a ternary operator. Ternary operators are good for when you have if/else statements with very simple/limited logic, which I don't think applies here.

## Conclusion
Let me know if you have any follow-up questions on the above, or if I missed any points/questions from your original post!

**Comment by ngal2021** [comment]
Hi @susanBuck! Thank you so much for looking at my code. After reloading all my files and the page, it worked for me too! I did add some code related to session data for radio buttons prior to your review, so that might have impacted the code in some way, but I think it was an error on my side not refreshing/saving every file I was working with. I'll make sure going forward that I check everything/reload VS Code as well.

## Note 1 - implemented and worked; Note 3 - helpful info about ternary operators
Thank you, this is super helpful! I wasn't sure how to utilize two different boolean values in one conditional, and this makes much more sense. I revised my code (and pushed a copy of it to GitHub) with the changes. 

In one of my iterations, I was incorrectly trying an `if else` conditional $winner, and then a separate `if` conditional for $tie. I think that was the reason why the code went through the winner conditional and then still went through the $tie conditional, when I didn't want it to, so it was outputting tie even when the user lost.

## Note 2 - implemented in 2 ways; follow up question about style/design?
I made the suggested revisions to my code in two ways, and I have a follow up question about which would be better for style/design.

In one version, I implemented the way you suggested: [One results variable, with string comparisons in the HTML](https://github.com/ngal2021/e2/commit/1d014336ab719081fbcf5abb425d576946a649f4#diff-3946ca64ff78d93ca61090a437cbb6b3d2ca0d488f5f9ccf3059608368b27693)
- I think this version is the most concise code with less unnecessary, null variables.

In another version, which is the version of the code I edited for the above version, I created and passed more variables to the view. Here is the commit for the version with multiple variables: [Working with variables for all data](https://github.com/ngal2021/e2/commit/fcb5c8ddb866df7534a9a65b50c7e467e34a54d2#diff-3946ca64ff78d93ca61090a437cbb6b3d2ca0d488f5f9ccf3059608368b27693)
- The downside, is that there are null variables always being passed whenever the game is played. The benefit of this version is that in the HTML, the PHP islands contain only PHP variables, so there might be less of a chance for someone to manipulate the output client side by editing the HTML (though I think that would only impact their copy of the HTML).


### Thank you again for all of the support!

**Comment by susanBuck** [comment]
I think the _"one results variable, with string comparisons in the HTML"_ version is the way to go here 👍

The code in your PHP islands is never actually accessible to the user - all of that gets processed on the server before it's delivered to the browser. Given that, there's no need for concern about user manipulation. 

Tip: Sometimes it can be helpful to do a "View Source" in your browser on the page and just see the final output that the user/browser sees. 

np on the support - thanks for your clear/thoughtful questions!

**Comment by ngal2021** [comment]
@susanBuck, thank you for the clarification and for the tip to check out "View Source"!
