### ISSUE TITLE
Project 2 - Multiple forms best practice and restart button

### ISSUE THREAD

**Issue by harrison2705** [susanBuck/e2-fall21#48]
Hi Susan, 

I have two questions:

1- Should we have a "process.php" file for each form of the page? Is there any possible way to include them all in one single php file? I've read a discussion on Stackoverflow but I don't know how we can handle $_SESSION[ ] parts. I find it easier to manage forms with multiple php files but what if an actual project has many forms, how can they control them well?

2 - I'm planning to add a button for the player to restart the game. I actually do not need to store any input as there is only one submit button and I made it work by simply adding 1 line **header('Location: index.php)** in the **process_playAgain.php** handling the Restart button. I think it makes sense but I do not know if there is any better approach to do that. Do you have any suggestions?

Many thanks

**Comment by susanBuck** [comment]
Hi @harrison2705 -

## Q1
It's possible to handle multiple different form submissions with one "process" file. You would just need some way to determine which form the submission was coming from so the process fille could determine the appropriate action to take.

For example, in your case it looks like form 1 is where the player enters the name and form 2 is where they play the game.

So in a single process file, you could look for the presence of some data from form 1 to determine if form 1 is where the submission is coming from, and execute whatever code is necessary for that form. Otherwise, you can assume the submission is coming from form 2, and execute the code necessary for that form.

Here's roughly what that would look like:
```php
# If namePlayer is present in our POST data, we can assume the submission came from form 1
if(isset($_POST['namePlayer']) {
    # Code here to handle form 1
else {
     # Code here to handle form 2
}
```

In this case a single "process" file for multiple files is fine since neither forms require a ton of work. But, if you were dealing with more complicated forms, it'd probably be better to just have two different files in charge of processing the respective form. 

## Q2 
It sounds like you just need a button that acts as a link that would take the user back to index.php.

My preferred method of doing this is just having a regular link that's styled to look like a button with CSS. 

Alternatively, you could add a small amount of Javascript inline with the HTML to make this happen:

```html
<input type="button" onclick="location.href='index.php';" value="Play Again">
```

Or, expanding on how you've done it, rather than introducing the extra `process_playAgain.php` file, simply have your "play again" form submit to "index.php" which would have the same effect of taking the user to "index.php" when they click the button.

Technically any of the above solutions work and are acceptable - I think it comes down to preference.

Let me know if you have any additional questions related to the above!
