### ISSUE TITLE
Project 2 - Notice: Undefined Index

### ISSUE THREAD

**Issue by harrison2705** [susanBuck/e2-fall21#50]
Hi Susan, 

There is one issue that I have not found a solution yet. I tried to use the **isset()** functions to fix the "_Notice: Undefined Index_", but it keeps showing when the page is loaded for the first time. 

I followed some online tutorials but their methods do not work for me. 
(https://www.stechies.com/undefined-index-error-php/).

Can you please give me a hint for this?

Thank you very much!

**Comment by susanBuck** [comment]
Hi @harrison2705 - 

Instead of:

```php
if (!is_null($_SESSION['resultsName'])) {
```

Try:

```php
if (isset($_SESSION['resultsName'])) {
```

Same thing for resultsOptions... Instead of:

```php
} elseif (!is_null($_SESSION['resultsOptions'])) {
```

Try: 
```php
} elseif (isset($_SESSION['resultsOptions'])) {
```

You want to use `isset` instead of `!is_null` because it will determine if a variable is set *AND* it's not null (ref: https://www.php.net/manual/en/function.isset.php).

Here's the docs for both _isset_ and _is_null_for more on this:

+ https://www.php.net/manual/en/function.isset.php
+ https://www.php.net/manual/en/function.is-null.php

Also, here's a post I made a few weeks ago that's related to this question: [forms-c : Small bug fix](https://github.com/susanBuck/e2-fall21/issues/39).

Some other notes while I was skimming your code:

It's not ideal to have so much of the view code embedded in functions (*display_name*, *display_option*) in the controller. 

Instead, just put that view code directly in the view where it's needed. For example, instead of

```php
<?php echo display_option();?>
```

Just have the actual form code:

```html
<form method = 'POST' action = 'process_name.php' class = 'form'>
<div>
    <label for = 'namePlayer'>Can you please tell us your name?</label>
    <input type = 'text' id = 'namePlayer' name = 'namePlayer'>
    <button type = 'submit' name='submitName'>Let's go!</button>
</div>
</form>
```

Let me know if you have any questions about the above notes or if switching to *isset* doesn't do the trick!

**Comment by harrison2705** [comment]
It works perfectly, Susan! 
The reason why I tried to use a function to display the form because I want to avoid repetition and remove long blocks of code. I found it hard to read when there are many of the view code embedded in functions too, but I am not sure if I do not use functions, will it be considered redundant code?

Thank you for your support!

**Comment by susanBuck** [comment]
It's good you're aware of/thinking about redundant code. : )

To address the redundant view code we can apply a technique I haven't showed yet which is to use "subviews".

To do this, you would extract the form code that you're using in multiple places into its own "subview" file - e.g. form-view.php, then import it where you need it in your main view file:

For example:

```html
<h2>Play again?</h2>
<p>Please click to choose your option!</p>
<?php require 'form-view.php' ?>
```

Does that make sense?

**Comment by harrison2705** [comment]
Ah, I got it. I will explore the technique and apply it for my project. Thanks again. It totally makes sense!

**Comment by susanBuck** [comment]
Closing this thread but feel free to re-open or start a new thread if there are any pending questions.
