### ISSUE TITLE
Week 9 - Unknown errors (Everything works, but curious to know the error reasons)

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e2-fall21#52]
Hi **Susan**,

I have followed your lecture video and have installed the 'Composer', but ran into a couple of errors (everything works, but not sure about these errors) and I don't know if you or someone have seen these -

(1) While downloading the repo from Susan Buck repo

![image](https://user-images.githubusercontent.com/64241541/139184007-402f4d37-f274-4623-b12c-9c8e3994866c.png)

(2) Composer Issue while updating the version from 0.1.5 to 0.1.6 in the composer.json file -

![image](https://user-images.githubusercontent.com/64241541/139184319-5a454a4e-1004-42ef-89fb-a1927072d10c.png)

Thanks,

Murthy

**Comment by susanBuck** [comment]
Hi @mgarimelHES -

# #1
Looks like a zip extension is missing. Not sure why I didn't run into that same error on my end since presumably everything on our servers should be the same. 

I had gone through some tests of different ways of installing Composer, so it's possible I had inadvertently installed the zip extension already.

Regardless, to address the warning you can install the extension with this command:

```bash
sudo apt install php-zip
```

(FYI - The reason it was still able to download the package without the zip extension is it just downloaded a larger, unzipped version)


# #2
The latest version of the RPS package is 0.1.5 - there is no 0.1.6. I think I mentioned 0.1.6 in lecture but was just giving an example of a hypothetical version jump.

If you go to the "releases" page for a package - e.g., https://github.com/susanBuck/rock-paper-scissors/releases - you can see what version numbers are available.

**Comment by mgarimelHES** [comment]
Thanks, regarding #2, I am trying to do the same like in the lecture - but it fails.

**Comment by susanBuck** [comment]
Are you referring to the [Week 9, Part 7](https://www.youtube.com/embed/O7mTY8hFAnA?rel=0&showinfo=0) video at the 13:00 minute mark?

At this part of the video, when speaking I did amend the version number to 0.1.6 because I was speaking hypothetically as if the package had an update to 0.1.6.

However, I quickly reverted it back to 0.1.5 before talking about running `composer update`. I never actually tried to run `composer update` with it set to version 0.1.6.

If you meant a different part of the videos, let me know. : )

**Comment by mgarimelHES** [comment]
Thanks, I missed the part of reverting back to 0.1.5.  :-)

**Comment by susanBuck** [comment]
In your defense - that part did get a little confusing because I was switching between the context of "I" as the developer _using_ the package and "I" as the developer who _created_ the package. :-)
