### ISSUE TITLE
Trouble accessing properties and methods from Game

### ISSUE THREAD

**Issue by lyonsco** [susanBuck/e2-fall21#54]
Hi, I'm really struggling through this week's materials. I have a lot of questions, but one specific one is how to access the results from the Game class. 

In class we saw how var_dump($game->play('scissors')) outputs an array of results; but I don't understand how to access those specific results. For example, I want to create a variable to display the $outcome, but I am getting an undefined error when I use

var_dump($game->$outcome);

I also tried to access the getResults() method, but I keep getting NULL. 

var_dump($game->getResults());

Any guidance would be appreciated. Thank you!

**Comment by susanBuck** [comment]
Hi @lyonsco -

Because`$game->player('scissors')` yields an array, you can access data from it just like any other array using square bracket notation. 

For example, if you wanted the _outcome_:

```php
$results = $game->play('scissors');

var_dump($results['outcome']);
```

In regards to using the _getResults_ method, this will only work if you set the `$persistResults` constructor parameter to true. For example:

```php
$game = new Game(true); # ← Note the addition of `true` here

var_dump($game->getResults();
```

Some useful details about this in the package documentation at https://github.com/susanBuck/rock-paper-scissors. It explains the *$persistResults* constructor parameter and the _getResults_ method.

Hope this helps. Let me know if you have follow-up Qs.

**Comment by lyonsco** [comment]
@susanBuck Thank you!  I knew I was missing something simple.

**Comment by susanBuck** [comment]
np! Glad you asked about it. Sometimes even the "simple" things aren't obvious when you're trying to distill a lot of new concepts!
