### ISSUE TITLE
403 Forbidden Message for /products

### ISSUE THREAD

**Issue by abarry25** [susanBuck/e2-fall21#62]
Hi all - Just outlining an issue I can across while working through class content today. I was receiving a 403 Forbidden message when utilizing the Products route, in routes.php: 

```php
return [
    # Ex: The path `/` will trigger the `index` method within the `AppController`
    '/' => ['AppController', 'index'],
    '/contact' => ['AppController', 'contact'],
    '/about' => ['AppController', 'about'],
    '/products' => ['ProductsController', 'index'],
];
```

To solve, I changed the name from Products to Product. @susanBuck , curious why this might be throwing this error? Would it have something to do with products being private within the framework? Thanks! 

Alexa

**Comment by susanBuck** [comment]
Hi @abarry25 -

When you said you changed the name - do you mean the name of the controller (`ProductsController` -> `ProductController`) or the URL pattern (`/products` -> `/product`)?

**Comment by abarry25** [comment]
@susanBuck - the URL pattern

**Comment by susanBuck** [comment]
Hm, odd - it should work with `/products` - that's how it's set up in my example: http://e2zipfoods.hesweb.xyz/products

Can you change it back to `products` and update your code on Github so I can see it failing to debug?

**Comment by abarry25** [comment]
@susanBuck https://github.com/abarry25/e2/tree/main/zipfoods

**Comment by susanBuck** [comment]
Thanks!

Any chance you have a folder called "products" in your "public" directory?

I was able to reproduce the 403 error by creating an empty directory at "e2/zipfoods/public/products/"

Reason why: The presence of a "products" directory in "public" has precedence over the routing system - and when it tries to load that directory, if there's no index file to load, it shows "403 forbidden" because the server is configured not to show the contents of a directory.

**Comment by abarry25** [comment]
I do! It was the "products" folder from the zip file for ZipFoods? Is there a better place for that?

**Comment by susanBuck** [comment]
It should be in `/public/images` :)

**Comment by abarry25** [comment]
That makes sense - a silly error! Thank you @susanBuck!
