### ISSUE TITLE
Understanding passing variables between classes and controllers

### ISSUE THREAD

**Issue by ngal2021** [susanBuck/e2-fall21#64]
I would like clarification on the connection between Products.php and ProductsController.php, specifically in regard to passing the $dataSource variable.

```php
$productsObj = new Products($this->app->path('/database/products.json'));
```

In pseudocode, here is my understanding of the above code from ProductsController.php.

1. We are creating a variable for a new 'object', `$productsObj`, that represents a new instance of the Products class, `new Products`. 

2. The `$dataSource` variable is a required argument for the construct_ function of the Products class, `public function __construct($dataSource)`. For this variable's value, we are passing the absolute path of the json database file `($this->app->path('/database/products.json')`. 
---> So in this instance, I think $dataSource = ($this->app->path('/database/products.json').

3. The construct_ function is when the Products function is called on the Products class, or when the function of the same name as the class is called on itself. 
---> So if there was a class called Icecream, the __construct function could be called in a controller with syntax like `new Icecream`?

I've copied the code below for reference. I would appreciate feedback of whether I am on the right track with understanding the relationship between classes and controllers. Thank you for the feedback!

### ProductsController.php
Absolute path: `zipfoods/apps/controllers/ProductsController.php`
```php
<?php

namespace App\Controllers;

use App\Products;

class ProductsController extends Controller {

    public function index() 
    {
        $productsObj = new Products($this->app->path('/database/products.json'));

        var_dump($productsObj);
        
        return $this->app->view('products/index');
    }
}
```

### Products.php 
Absolute path: `zipfoods/app/Products.php`

```php
<?php

namespace App;

class Products
{
    # Properties
    public $products = [];

    # Methods
    public function __construct($dataSource)
    {
        $json = file_get_contents($dataSource);
        $this->products = json_decode($json, true);
    }

    public function getAll()
    {
        return $this->products;
    }

    public function getById(int $id)
    {
        return $this->products[$id] ?? null;
    }

    public function getBySku(string $sku)
    {
        $productId = array_search($sku, array_column($this->products, 'sku', 'id'));
        return $this->getById($productId);
    }
}
```

**Comment by susanBuck** [comment]
Hi @ngal2021 -

You are 100% correct in your understanding of the first 2 points.

For point 3, I think you're on the right track, but I'm a little confused by your wording, so I just want to clarify:

A `__construct` function is automatically invoked when a new instance of a class is created.

So yes, if we saw code like:

```php
$iceCreamObj = new IceCream();
```

We can assume the `__construct` method within the IceCream class would be invoked, simply because a new instance of that class was created.

(Of course, this all assumes that the class in question has a `__construct` method, which is not required.)

**You can think of the `__construct` method as a ”setup” method - it's designed to do any of the setup work we might want to accomplish when a new instance of a class is created.**

Hope this helps clarify things! Let me know if you have follow-up questions.

**Comment by ngal2021** [comment]
@susanBuck, thank you! Thinking of `__construct` as a "setup" method is really helpful for my understanding.

**Comment by susanBuck** [comment]
@ngal2021 np! Knowing this was helpful, I'll start using "setup" as a way of describing the construct method in future semesters. 👍

**Comment by mgarimelHES** [comment]
I may say *initialize* the object as a part of the 'construct'.
