### ISSUE TITLE
Lecture 1 - Mac - bash $ vs zsh % prompt

### ISSUE THREAD

**Issue by owen-mcg** [susanBuck/e2-fall21#9]
**Comment about command line**

Hello all! I wanted to comment, most likely superfluously, that Mac Terminal uses zsh (Z shell) by default, rather than Bash. While there are differences, I've not come across any Bash command that won't run in zsh. 

That being said, a potentially confusing _visual_ difference is that Bash uses **$** before each command and zsh uses **%**. 

When macOS switched from Bash to zsh as the default, I was even more inexperienced with CL than I am now, and I was very confused. I'm guessing you all are probably not as inexperienced as I was, but hopefully this can help somebody. :)

PS @susanBuck, thank you for the primer. It cleared a lot of questions up for me about how CL works.

**Comment by susanBuck** [comment]
Thanks for this head's up, @owen-mcg! Making a note to tell students about zsh and the use of `%` next time around.

Glad you found the primer helpful. Let me know if you have any questions as you spend more time with CL.

**Comment by owen-mcg** [comment]
Thank you, @susanBuck, yeah super helpful. All of it was helpful, and the info about directories in particular. 

Oh, also, [here's how to switch to bash on macOS if you are so inclined](https://www.howtogeek.com/444596/how-to-change-the-default-shell-to-bash-in-macos-catalina/). There are consequences for doing this, and I know nothing about them! @susanBuck will it break anyone's computer?

**Comment by susanBuck** [comment]
Nope, switching between zsh and bash (or bash and zsh) shouldn't cause any notable harm.

Only word of caution is if you've done any customizations to your bash, they might not work as expected in zsh. This was the situation I was in and why I hadn't yet made the switch to zsh yet. Some of the configs I had for bash weren't working in zsh, and I've been meaning to go through and make the necessary changes so I could do the switch. You bringing this up motivated me to do so, and I'll now be using zsh moving forward. :-)

If you're curious about the customizations, here are more details:

In a config file you can do things like customize the style of your prompt and create aliases for commonly used commands.

If you're using bash, these customizations can be made in the file `~/.bash_profile`.
If you're using zsh, they can be made in `~/.zshrc`.

[Here's a version of the config file I use...](https://gist.github.com/susanBuck/b83bdde2b173b829a78e52b6fb02576f)

Note on line 42 is where I customize the prompt and force it to use a `$` at the end instead of `%` (just because that's what I'm used to :-)

**Comment by mgarimelHES** [comment]
I have used **Brackets** before for another class, it is pretty good tool as well. You may check out the [Brackets...](https://brackets.io) for more details in case someone is interested!

**Comment by susanBuck** [comment]
@mgarimelHES Thanks for sharing! I've checked out Brackets in the past and appreciated its clean interface. I'd say it's a more front-end focussed editor, but definitely with a lot of capabilities.
